"""
Generate a markdown summary of MLflow runs for a given experiment.
Output is saved to experiments/runs_summary.md.
"""

from pathlib import Path

import mlflow

from src.utils.logger import logger


def generate_run_report(
    experiment_name: str = "churn_prediction",
    tracking_uri: str = "sqlite:///mlruns.db",
    output_path: str = "experiments/runs_summary.md",
    top_n: int = 10,
) -> None:
    """Query MLflow and write a markdown summary of the top N runs."""
    mlflow.set_tracking_uri(tracking_uri)

    experiment = mlflow.get_experiment_by_name(experiment_name)
    if not experiment:
        logger.warning(f"Experiment '{experiment_name}' not found in MLflow.")
        return

    runs = mlflow.search_runs(
        experiment_ids=[experiment.experiment_id],
        order_by=["metrics.accuracy DESC"],
        max_results=top_n,
    )

    if runs.empty:
        logger.warning("No runs found.")
        return

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f"# MLflow Run Summary — {experiment_name}",
        f"\nTop {min(top_n, len(runs))} runs by accuracy.\n",
        "| Run ID (short) | Accuracy | Precision | Recall | n_estimators | max_depth | Status |",
        "|---|---|---|---|---|---|---|",
    ]

    for _, row in runs.iterrows():
        short_id = row["run_id"][:8]
        acc = f"{row.get('metrics.accuracy', 0):.4f}"
        prec = f"{row.get('metrics.precision', 0):.4f}"
        rec = f"{row.get('metrics.recall', 0):.4f}"
        n_est = row.get("params.n_estimators", "—")
        depth = row.get("params.max_depth", "—")
        status = row.get("status", "—")
        lines.append(f"| {short_id} | {acc} | {prec} | {rec} | {n_est} | {depth} | {status} |")

    lines += [
        "\n---",
        f"\n_Generated by `src/utils/run_report.py` | Tracking URI: `{tracking_uri}`_",
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    logger.info(f"Run report saved to {output_path}")


if __name__ == "__main__":
    generate_run_report()
